# Generated by Django 5.2 on 2025-04-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fahrzeug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kennzeichen",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Kennzeichen"
                    ),
                ),
                (
                    "hersteller",
                    models.CharField(max_length=50, verbose_name="Hersteller"),
                ),
                ("modell", models.CharField(max_length=50, verbose_name="Modell")),
                ("baujahr", models.PositiveIntegerField(verbose_name="Baujahr")),
                (
                    "fahrgestellnummer",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        verbose_name="Fahrgestellnummer (FIN)",
                    ),
                ),
                (
                    "kilometerstand",
                    models.PositiveIntegerField(verbose_name="Kilometerstand"),
                ),
                (
                    "kraftstoffart",
                    models.CharField(
                        choices=[
                            ("B", "Benzin"),
                            ("D", "Diesel"),
                            ("E", "Elektro"),
                            ("H", "Hybrid"),
                        ],
                        max_length=1,
                        verbose_name="Kraftstoffart",
                    ),
                ),
                (
                    "getriebeart",
                    models.CharField(
                        choices=[("M", "Manuell"), ("A", "Automatik")],
                        max_length=1,
                        verbose_name="Getriebeart",
                    ),
                ),
                ("farbe", models.CharField(max_length=30, verbose_name="Farbe")),
                (
                    "sitzanzahl",
                    models.PositiveSmallIntegerField(verbose_name="Anzahl Sitze"),
                ),
                (
                    "tueranzahl",
                    models.PositiveSmallIntegerField(verbose_name="Anzahl Türen"),
                ),
                (
                    "erstzulassung",
                    models.DateField(verbose_name="Datum der Erstzulassung"),
                ),
                (
                    "naechste_hauptuntersuchung",
                    models.DateField(verbose_name="Nächste Hauptuntersuchung (TÜV)"),
                ),
                (
                    "versicherer",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Versicherung",
                    ),
                ),
                (
                    "versicherungsnummer",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Versicherungsnummer",
                    ),
                ),
                (
                    "mietpreis_pro_tag",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Mietpreis pro Tag (€)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verfügbar", "Verfügbar"),
                            ("vermietet", "Vermietet"),
                            ("wartung", "In Wartung"),
                            ("nicht_verfügbar", "Nicht verfügbar"),
                        ],
                        default="verfügbar",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "bemerkungen",
                    models.TextField(blank=True, null=True, verbose_name="Bemerkungen"),
                ),
            ],
            options={
                "verbose_name": "Fahrzeug",
                "verbose_name_plural": "Fahrzeuge",
                "ordering": ["kennzeichen"],
            },
        ),
    ]
