# Generated by Django 5.2 on 2025-04-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fahrzeug",
            name="fahrzeugschein",
            field=models.FileField(blank=True, null=True, upload_to="fahrzeugscheine/"),
        ),
        migrations.AddField(
            model_name="fahrzeug",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fahrzeug-fotos/"),
        ),
    ]
